//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer ObjectConstants
// {
//
//   row_major float4x4 MVP;            // Offset:    0 Size:    64
//   float3 ColorOverride;              // Offset:   64 Size:    12 [unused]
//   float ColorOverrideAmount;         // Offset:   76 Size:     4 [unused]
//   float2 UVScale;                    // Offset:   80 Size:     8 [unused]
//   float2 UVOffset;                   // Offset:   88 Size:     8 [unused]
//   row_major float4x4 World;          // Offset:   96 Size:    64 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// ObjectConstants                   cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xy          2     NONE   float   xy  
// NORMAL                   0   xyz         3     NONE   float   xyz 
// INSTANCE_WORLD           0   xyzw        4     NONE   float   xyzw
// INSTANCE_WORLD           1   xyzw        5     NONE   float   xyzw
// INSTANCE_WORLD           2   xyzw        6     NONE   float   xyzw
// INSTANCE_WORLD           3   xyzw        7     NONE   float   xyzw
// INSTANCE_COLOR           0   xyzw        8     NONE   float   xyzw
// INSTANCE_UV_SCALE        0   xy          9     NONE   float   xy  
// INSTANCE_UV_OFFSET       0   xy         10     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xy          2     NONE   float   xy  
// NORMAL                   0   xyz         3     NONE   float   xyz 
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xyz
dcl_input v1.xyzw
dcl_input v2.xy
dcl_input v3.xyz
dcl_input v4.xyzw
dcl_input v5.xyzw
dcl_input v6.xyzw
dcl_input v7.xyzw
dcl_input v8.xyzw
dcl_input v9.xy
dcl_input v10.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_output o2.xy
dcl_output o3.xyz
dcl_temps 2
mul r0.xyzw, v0.yyyy, v5.xyzw
mad r0.xyzw, v0.xxxx, v4.xyzw, r0.xyzw
mad r0.xyzw, v0.zzzz, v6.xyzw, r0.xyzw
add r0.xyzw, r0.xyzw, v7.xyzw
mul r1.xyzw, r0.yyyy, cb0[1].xyzw
mad r1.xyzw, r0.xxxx, cb0[0].xyzw, r1.xyzw
mad r1.xyzw, r0.zzzz, cb0[2].xyzw, r1.xyzw
mad o0.xyzw, r0.wwww, cb0[3].xyzw, r1.xyzw
mul o1.xyzw, v1.xyzw, v8.xyzw
mad o2.xy, v2.xyxx, v9.xyxx, v10.xyxx
mul r0.xyz, v3.yyyy, v5.xyzx
mad r0.xyz, v3.xxxx, v4.xyzx, r0.xyzx
mad o3.xyz, v3.zzzz, v6.xyzx, r0.xyzx
ret 
// Approximately 14 instruction slots used
